-- 스키마 조회
SHOW DATABASES;
 
-- 스키마 생성
CREATE DATABASE board; 
 
-- TB_BOARD 테이블 삭제
DROP TABLE board.TB_BOARD;
 
-- TB_BOARD 테이블 생성 및 코멘트 추가
CREATE TABLE board.TB_BOARD (
	  BOARD_SEQ INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '게시글 번호'
	, BOARD_RE_REF INT COMMENT '글의 그룹 번호'
	, BOARD_RE_LEV INT COMMENT '답변 글의 깊이'
	, BOARD_RE_SEQ INT COMMENT '답변 글의 순서'
	, BOARD_WRITER VARCHAR(20) COMMENT '게시글의 작성자'
	, BOARD_SUBJECT VARCHAR(50) COMMENT '게시글의 제목'
	, BOARD_CONTENT VARCHAR(2000) COMMENT '게시글의 내용'
	, BOARD_HITS INT UNSIGNED NOT NULL DEFAULT '0' COMMENT '게시글의 조회수'
	, DEL_YN VARCHAR(1) NOT NULL DEFAULT 'N' COMMENT '삭제유무'
	, INS_USER_ID VARCHAR(20) COMMENT '입력자ID'
	, INS_DATE DATETIME COMMENT '입력일시'
	, UPD_USER_ID VARCHAR(20) COMMENT '수정자ID'
	, UPD_DATE DATETIME COMMENT '수정일시'
	, PRIMARY KEY (BOARD_SEQ)
) COMMENT '게시판';
 
-- TB_BOARD 테이블 컬럼 정보 확인
SHOW FULL COLUMNS FROM board.TB_BOARD;
 
-- TB_BOARD 테이블 샘플 데이터 입력
INSERT INTO board.TB_BOARD (BOARD_RE_REF, BOARD_RE_LEV, BOARD_RE_SEQ, BOARD_WRITER, BOARD_SUBJECT, BOARD_CONTENT, INS_USER_ID, INS_DATE) VALUES (0, 0, 0, '게시글 작성자_1', '게시글 제목_1', '게시글 내용_1', 'NONMEMBER', NOW(), 'NONMEMBER', NOW() );
INSERT INTO board.TB_BOARD (BOARD_RE_REF, BOARD_RE_LEV, BOARD_RE_SEQ, BOARD_WRITER, BOARD_SUBJECT, BOARD_CONTENT, INS_USER_ID, INS_DATE) VALUES (0, 0, 0, '게시글 작성자_2', '게시글 제목_2', '게시글 내용_2', 'NONMEMBER', NOW(), 'NONMEMBER', NOW() );
INSERT INTO board.TB_BOARD (BOARD_RE_REF, BOARD_RE_LEV, BOARD_RE_SEQ, BOARD_WRITER, BOARD_SUBJECT, BOARD_CONTENT, INS_USER_ID, INS_DATE) VALUES (0, 0, 0, '게시글 작성자_3', '게시글 제목_3', '게시글 내용_3', 'NONMEMBER', NOW(), 'NONMEMBER', NOW() );
INSERT INTO board.TB_BOARD (BOARD_RE_REF, BOARD_RE_LEV, BOARD_RE_SEQ, BOARD_WRITER, BOARD_SUBJECT, BOARD_CONTENT, INS_USER_ID, INS_DATE) VALUES (0, 0, 0, '게시글 작성자_4', '게시글 제목_4', '게시글 내용_4', 'NONMEMBER', NOW(), 'NONMEMBER', NOW() );
INSERT INTO board.TB_BOARD (BOARD_RE_REF, BOARD_RE_LEV, BOARD_RE_SEQ, BOARD_WRITER, BOARD_SUBJECT, BOARD_CONTENT, INS_USER_ID, INS_DATE) VALUES (0, 0, 0, '게시글 작성자_5', '게시글 제목_5', '게시글 내용_5', 'NONMEMBER', NOW(), 'NONMEMBER', NOW() );
 
-- TB_BOARD 테이블 샘플 데이터 조회
SELECT *
  FROM board.TB_BOARD;