-- TB_BOARD_FILE 테이블 생성 및 코멘트 추가
CREATE TABLE BOARD.TB_BOARD_FILE (
	  BOARD_SEQ INT Not Null COMMENT '게시글 번호'
	, FILE_NO INT Not Null COMMENT '첨부파일 번호'
	, FILE_NAME_KEY VARCHAR(200) COMMENT '첨부파일 암호화명'
	, FILE_NAME VARCHAR(100) COMMENT '첨부파일명'
	, FILE_PATH VARCHAR(200) COMMENT '첨부파일 경로'
	, FILE_SIZE VARCHAR(50) COMMENT '첨부파일 크기'
	, REMARK VARCHAR(1000) COMMENT '비고'
	, DEL_YN VARCHAR(1) COMMENT '삭제유무'
	, INS_USER_ID VARCHAR(20) COMMENT '입력자ID'
	, INS_DATE DATETIME COMMENT '입력일시'
	, UPD_USER_ID VARCHAR(20) COMMENT '수정자ID'
	, UPD_DATE DATETIME COMMENT '수정일시'
	, PRIMARY KEY (BOARD_SEQ, FILE_NO) 
) COMMENT '게시판 첨부파일';
 
-- TB_BOARD 테이블 샘플 데이터 조회
SELECT *
  FROM BOARD.TB_BOARD_FILE;